CREATE TABLE ALUNOS(
    MATRICULA VARCHAR(9) NOT NULL,
    NOME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR (100) NOT NULL,
    TURMA CHAR (1) NOT NULL,
    SERIE INT NOT NULL,
    SEXO CHAR(1) NOT NULL,
    TELEFONE VARCHAR(15) NOT NULL,
    ENDEREÇO VARCHAR(100) NOT NULL,
    RESPONSAVEL VARCHAR(100) NOT NULL,
    PRIMARY KEY (MATRICULA)
);